# Generated by Django 4.1.5 on 2023-01-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tododemoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='date',
            field=models.DateField(default='1998-02-12'),
            preserve_default=False,
        ),
    ]
